### PR TITLE
Headers should't generate code.

### PR DESCRIPTION
**Pull request by CarloWood**
This is needed to avoid "Multiple instantiations of ..." linker errors (a lot of them).

Not sure why you want this library to be header only?

You can ignore the first commit (couldn't get rid of it in the pull request), or use it if
it doesn't break anything for you (as far as I know 'branch' is normally not used?)

### CODE REVIEW

**Comment by janekb04** [comment]
Hi, thanks for your PR! I completely forgot about this issue and I never had to include `glfwpp.hpp` from multiple TUs at once and didn't notice. I see that you made three changes, so let me comment;

1. You removed `branch` in `.gitmodules`. It is necessary there as examples rely on using the `docking` branch. Admittedly though, I think I will separate the dependencies of the examples and the dependencies of GLFWPP itself to make it clear that GLFWPP doesn't require ImGui, only some examples do.
2. You added a lot of `inline` and `gnu::always_inline` specifiers. They will not harm the code in any way, but I don't believe that they are necessary as modern compilers (which C++17 compilers are) should be able to see that these functions are so simple that they will always be inlined. This is one advantage of the library being header-only - we don't have to rely on complex and volatile link-time optimizations, as the full source code of functions is available at compilation time.
3. You created the `StaticEvent` class to solve ODR violations. I think that there may be an easier solution using `inline` variables (introduced in C++17) as, as far as I remember, this was their intended usage. I will have to try it myself and see.

**Comment by CarloWood** [comment]
Hi, thanks for your reply.

1. Yes, this is just a personal thing I need (to be removed). But I couldn't get rid of that commit when doing the pull request for some reason (I could have made a new branch and all, but I was lazy and thought: why not).
2. The `inline` keyword makes all the difference here, it will turn the code (functions) in a weak links, no longer causing linker collisions. I added the [[gnu::always_inline]] as an improvement for the case where you compile without optimization (which is what I'm currently doing, I just use -g. If you don't want it in your code for some reason then you can leave it out (it won't break linkage).
3. I never heard of inline variables, but when they work in the same way: make them weakly linked and leaving it to the linker to resolve them into a single instance then that would certainly be a better solution (using the template trick does the exact same thing).

**Comment by janekb04** [comment]
I applied fixes and pushed them to the `fix` branch. It should fix issues #16, #20, #79 and #80. Let me know if this solves your issues. If it does, we may close this PR and I will merge the `fix` branch.

**Comment by CarloWood** [comment]
On Sun, 01 Aug 2021 11:01:38 -0700
Jan Bielak ***@***.***> wrote:

> I applied fixes and pushed them to the `fix` branch. It should fix
> issues #16, #20, #79 and #80. Let me know if this solves your issues.
> If it does, we may close this PR and I will merge the `fix` branch.
> 

I did a pull request for 'fix'.

**Comment by janekb04** [comment]
Closed via #89 and #87.

**Pull request closed without merging**
